spring:
  application:
    name: social-network-api
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
jwt:
  secret: your-secret-key
logging:
  level:
    org.springframework.web: DEBUG
    com.example: DEBUG
    org.springframework.graphql: DEBUG
    org.springframework.boot.autoconfigure.graphql.servlet: DEBUG

